import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import "./globals.css";
import { currentUser } from "@clerk/nextjs/server";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const user = await currentUser()
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <div className="flex flex-row w-screen h-full">
            <div className="flex flex-col w-48 h-screen sticky top-0 bg-slate-100 text-cyan-800 px-2 py-3">
              <SignedIn>
                <div className="flex flex-row gap-2 items-center justify-start border-b-2 border-cyan-800 py-2">
                  <UserButton />
                  <Link href={'/'}>{user?.fullName}</Link>
                </div>
                <ul className="flex flex-col">
                  <Link href={'/createpost'}>
                    <button className="hover:translate-x-2 hover:underline transition-all ease-out 200ms">make a post</button>
                  </Link>
                  <Link href={'/myposts'}>
                    <button className="hover:translate-x-2 hover:underline transition-all ease-out 200ms">my posts</button>
                  </Link>
                </ul>
              </SignedIn>
              <SignedOut>
                <SignInButton>
                  <button className="py-3 bg-cyan-800 text-white rounded-md hover:scale-105 hover:shadow-md transition-all ease-in-out 200ms">Sign up?</button>
                </SignInButton>
              </SignedOut>
            </div>
            <div className="w-full h-full pt-3 text-cyan-800">
              {children}
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}

{/* <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn> */}